# Generated by Django 5.1 on 2024-08-31 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weel',
            new_name='Week',
        ),
    ]
