# Generated by Django 5.1 on 2024-08-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_rename_weel_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
        migrations.AddField(
            model_name='task',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
            preserve_default=False,
        ),
    ]
